version: '2'

services:

  wordpress:
    image: wordpress_app
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password