- name: Create ec2 security group
  ec2_group:
    name: "{{ security_group_name }}_{{ lookup('env','ENVIRONMENT') }}_{{ lookup('env','APP') }}"
    description: security group for wordpress
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: result

- name: copy
  copy: content="{{ result.group_id }}" dest="./security_group_id"
  
