- name: Provision a set of instances
  ec2:
    key_name: "{{ key_pair_name }}_{{ lookup('env','ENVIRONMENT') }}_{{ lookup('env','APP') }}"
    group: "{{ security_group_name }}_{{ lookup('env','ENVIRONMENT') }}_{{ lookup('env','APP') }}"
    instance_type: "{{ lookup('env','SERVER_SIZE') }}"
    image: "{{ lookup('env','EC2_IMAGE') }}"
    wait: true
    count: "{{ lookup('env','NUM_SERVERS') }}"
    instance_tags:
      Name: "{{ instance_tag }}_{{ lookup('env','ENVIRONMENT') }}_{{ lookup('env','APP') }}"
  register: ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=aws_host
  with_items: ec2.instances
  
- name: Wait for SSH to come up
  local_action: wait_for 
    host={{ item.public_ip }} 
    port=22 
    state=started
  with_items: ec2.instances

- name: Add the newly created EC2 instance(s) to the local host group
  local_action: lineinfile dest="./hosts" insertafter="[aws_host]" line="{{ item.public_ip }} id={{ item.id }}"
  with_items: ec2.instances