# Docker
  
- name: Add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' filename=docker
  become: true
  
- name: Add apt-get key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Run apt-get update and install docker
  apt: name=docker-engine=1.10.3-0~trusty update_cache=yes
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5
  
# Python pip

- name: Run apt-get to install pip
  apt: name=python-pip
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5
  
- name: Install docker-py
  pip: name=docker-py
  become: yes
  
# Docker compose
- name: Install docker-compose
  pip: name=docker-compose
  become: yes
